---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: duckling
  labels:
    app: botfront
    component: duckling
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: botfront
        component: duckling
    spec:
      containers:
      - name: duckling
        image: botfront/duckling:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: botfront-common
        - configMapRef:
            name: botfront-duckling
        - configMapRef:
            name: botfront-env
        - secretRef:
            name: botfront
        env:
        - name: PORT
          value: "8000"
        ports:
        - containerPort: 8000
          name: api
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
      restartPolicy: Always
