---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: botfront
    component: api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: botfront
        component: api
    spec:
      containers:
      - name: api
        image: botfront/botfront-api:v0.18.5
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: botfront-common
        - configMapRef:
            name: botfront-api
        - configMapRef:
            name: botfront-env
        - secretRef:
            name: botfront
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: api
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
          limits:
            cpu: "1.0"
            memory: "512Mi"
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
      restartPolicy: Always
